// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfqhspnyejzohxwaqnyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcWhzcG55ZWp6b2h4d2FxbnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NTQ2NjksImV4cCI6MjA4NDUzMDY2OX0.yuFMCxVKrD4we1LlPXWBx3vETi2OIcurG7DjtLSTXB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});